#:schema https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

version = 2
final_space = true
console_title_template = '{{ .Shell }} in {{ .Folder }}'

[[blocks]]
  type = 'prompt'
  alignment = 'left'

[[blocks.segments]]
  type = 'path'
  style = 'plain'
  foreground = 'p:purple'
  background = 'transparent'
  template = '{{ .Path }} '

[blocks.segments.properties]
  style = 'agnoster_full'

[[blocks.segments]]
  type = 'git'
  style = 'plain'
  foreground = 'p:black'
  background = 'p:green'
  template = " {{ .HEAD }} <#FFF,transparent> </>"

[blocks.segments.properties]
  branch_icon = ''
  branch_max_length = 25

[[blocks.segments]]
  type = "text"
  style = "plain"
  foreground = "p:green"
  template = "❯"

[[blocks]]
  type = "rprompt"
  alignment = "right"

[[blocks.segments]]
  type = "shell"
  style = "plain"
  foreground = "p:gray"
  template = "{{.Shell}}"

[[blocks.segments]]
  type = "text"
  style = "plain"
  foreground = "p:gray"
  template = "/"

[[blocks.segments]]
  type = "os"
  style = "plain"
  template = "{{.Icon}}"

[blocks.segments.properties]
  debian = "<p:red,transparent>debian</>"
  windows = "<p:blue,transparent>windows</>"

[palette]
  black = '#262B44'
  blue = '#0079D5'
  green = '#D8FC5C'
  purple = '#885CFC'
  orange = '#F07623'
  red = '#CE0056'
  white = '#E0DEF4'
  yellow = '#F3AE35'
  gray = '#878787'
